version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test

workflows:
    tests:
      jobs:
        - test